#include<stdio.h>
int main()
{
    //freopen("1.out","w",stdout);
    int arr[3][4];
    int i,j;
    for(i=0;i<3;i++)
    {
        for(j=0;j<4;j++)
        scanf("%d",&arr[i][j]);
    }
    double p[3]={0};
    for(i=0;i<3;i++)
    {
        for(j=0;j<4;j++)
        {
            p[i]+=(double)arr[i][j];
        }
        p[i]=p[i]/4.0;
    }
    if(p[0]>p[2]&&p[0]>p[1])
    {
        for(j=0;j<4;j++)
        {
            printf("%d",arr[0][j]);
            if(j!=3)printf(",");
        }printf("\n");
        if(p[2]>p[1])
        {
            for(j=0;j<4;j++)
        {
            printf("%d",arr[2][j]);
            if(j!=3)printf(",");
        }printf("\n");
            for(j=0;j<4;j++)
        {
            printf("%d",arr[1][j]);
            if(j!=3)printf(",");
        }printf("\n");
        }
        if(p[1]>p[2])
        {
            for(j=0;j<4;j++)
        {
            printf("%d",arr[1][j]);
            if(j!=3)printf(",");
        }printf("\n");
            for(j=0;j<4;j++)
        {
            printf("%d",arr[2][j]);
            if(j!=3)printf(",");
        }printf("\n");
        }
    }
    if(p[2]>p[0]&&p[2]>p[1])
    {
        for(j=0;j<4;j++)
        {
            printf("%d",arr[2][j]);
            if(j!=3)printf(",");
        }printf("\n");
        if(p[0]>p[1])
        {
            for(j=0;j<4;j++)
        {
            printf("%d",arr[0][j]);
            if(j!=3)printf(",");
        }printf("\n");
            for(j=0;j<4;j++)
        {
            printf("%d",arr[1][j]);
            if(j!=3)printf(",");
        }printf("\n");
        }
        if(p[1]>p[0])
        {
            for(j=0;j<4;j++)
        {
            printf("%d",arr[1][j]);
            if(j!=3)printf(",");
        }printf("\n");
            for(j=0;j<4;j++)
        {
            printf("%d",arr[0][j]);
            if(j!=3)printf(",");
        }printf("\n");
        }
    }
    if(p[1]>p[2]&&p[1]>p[0])
    {
        for(j=0;j<4;j++)
        {
            printf("%d",arr[1][j]);
            if(j!=3)printf(",");
        }printf("\n");
        if(p[2]>p[0])
        {
            for(j=0;j<4;j++)
        {
            printf("%d",arr[2][j]);
            if(j!=3)printf(",");
        }printf("\n");
            for(j=0;j<4;j++)
        {
            printf("%d",arr[0][j]);
            if(j!=3)printf(",");
        }printf("\n");
        }
        if(p[0]>p[2])
        {
            for(j=0;j<4;j++)
        {
            printf("%d",arr[0][j]);
            if(j!=3)printf(",");
        }printf("\n");
            for(j=0;j<4;j++)
        {
            printf("%d",arr[2][j]);
            if(j!=3)printf(",");
        }printf("\n");
        }
    }
    return 0;
}